source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target ‘version1’ do
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'MBProgressHUD', '~> 0.9.2'
  pod 'Alamofire', '~> 3.0.0’
  pod 'SwiftyJSON', '~> 2.3.0'
  pod 'SDWebImage', '~>3.7'
pod 'TTTAttributedLabel'
end



